# action.yml
name: 'Arch Linux Builder Action'
description: 'Arch Linux build environment that supports execution of custom scripts as well as building AUR packages, repository management and signing'
inputs:
  action:
    description: 'The action to perform: build-package, build-repo, build-aur, exec'
    required: true
    default: 'build-package'
  target:
    description: 'Target to build. For `build-package`, this is a directory containing a `PKGBUILD`, for `build-aur` these are package names to be fetched from AUR (passed to `paru`), for `build-repo`, this is a directory containing package files, for `exec`, these are arguments for an exec call.'
    required: true
    default: '.'
  artifacts:
    description: 'Output artifacts are placed here. For `build-repo` this is the database name.'
    required: true
    default: 'output'
  packager:
    description: 'For `build-package`: Specify the packager name'
    required: false
    default: "GitHub Actions Packager <github@example.com>"
  gpgsign:
    description: 'GPG Key to use for signing packages or repository files'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/marcoh00/archlinux-builder:latest'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.target }}
    - ${{ inputs.artifacts }}
    - ${{ inputs.gpgsign }}
    - ${{ inputs.packager }}
branding:
  icon: 'loader'
  color: 'blue'
